### ISSUE TITLE
Confused about this project's relationship to PHPDave11's gofpdf

### ISSUE THREAD

**Issue by yujiri8** [go-pdf/fpdf#17]
https://github.com/phpdave11/gofpdf

This project appears to be a fork of that one but doesn't mention it anywhere?

**Comment by sbinet** [comment]
it's actually a fork of https://github.com/jung-kurt/gofpdf.
for [gonum/plot](https://github.com/gonum/plot), we used at some point the `phpdave11/gofpdf` fork but it didn't integrate some needed PRs of ours, so I forked off `jung-kurt/gofpdf`:

- https://github.com/phpdave11/gofpdf/pull/15
- https://github.com/phpdave11/gofpdf/pull/16
(the performance improvements were quite interesting)

at the bottom of the `README`, we do thank the original repo, but, indeed, without an explicit link to it.
I'll fix that shortly.

(AFAIK, we did retain all the correct copyleft/copyrights from the original author. Let me know, if that isn't the case, and I'll fix that as well.)

**Comment by sbinet** [comment]
(feel free to reopen if the PR I've just merged isn't what you expected)

**Comment by flibustenet** [comment]
Why on github we don't see that it's a fork ? I mean we cannot see the diff like on phpdave11 page we see "9 commits ahead, 2 commits behind jung-kurt:master."
It could be fine if the two forks could merge if possible.

**Comment by sbinet** [comment]
it's because I tried to have a clean slate for tags (restarting at `v0.x.0`, so I could clean up a bit the API that I found to be a bit cluttered) and didn't succeed to do so w/o severing the ties with the original.
(FWIW, in the end, the solution was to use a `go mod` thing: `retract`.)

considering that [phpdave11/gofpdf](https://github.com/phpdave11/gofpdf) hasn't merged a single PR in more than a year, I don't think merging the PRs that went into `go-pdf/fpdf` into `phpdave11/gofpdf` is really something that can happen with some good amount of certainty :)
