### ISSUE TITLE
Are there any notes on how this fork is different from the original gofpdf?

### ISSUE THREAD

**Issue by shkvoretz** [go-pdf/fpdf#53]
Are there any notes on how this fork is different from the original gofpdf?

Thanks

**Comment by nz-v** [comment]
Differences between `go-pdf/fpdf` and the original FPDF library:

1. **Error Handling**: In the original FPDF library, errors are typically handled by causing the program to panic. In contrast, `go-pdf/fpdf` employs a more controlled error handling approach. It sets an internal error field when errors occur and generally returns without further operations, allowing users to handle errors explicitly.

2. **Buffer Usage**: `go-pdf/fpdf` optimizes memory management by using `bytes.Buffer` to construct page content. This approach is more memory-efficient than string concatenation, which is often used in the original FPDF library.

3. **Output Generation**: `go-pdf/fpdf` offers flexibility in directing the PDF output. It utilizes the `io.Writer` interface, allowing users to specify where the generated PDF should be written, whether it's to a file, network connection, or other destinations.

4. **Font Definitions**: Font definition files in `go-pdf/fpdf` are stored in JSON format, while the original FPDF library uses PHP for font definitions. This format change simplifies font management and compatibility with Go.

5. **Function Names**: Despite Go idioms that might suggest different function names, `go-pdf/fpdf` often retains API names from the original FPDF library. For example, it uses `pdf.GetX()` instead of a simpler `pdf.X()`.

This information is also available in the [Conversion Notes](https://github.com/go-pdf/fpdf/blob/main/README.md#conversion-notes) section of the documentation.

**Comment by shkvoretz** [comment]
@nz-v this is great! Thanks for such a comprehensive response! 🙏🏻

**Comment by nnzv** [comment]
Close the issue if no inconveniences are present.

CC: @sbinet
